os:
  - linux
  # - osx

script:
  - chmod 777 ./install.sh
  - travis_wait 720 ./install.sh -y
  - source ~/.bashrc
  - g++ --version
  - cmake --version
  - python --version
  - conda --version
  - make --version
